language: d
dist: trusty
sudo: false

matrix:
  include:
    - d: dmd-2.078.0
      env: [FRONTEND=2.078.0]
    - d: dmd-2.077.1
      env:
        - [FRONTEND=2.077]
        - [TEST_NONET=true]
    - d: dmd-2.076.1
      env:
        - [FRONTEND=2.076]
        - [COVERAGE=true]
    - d: dmd-2.075.1
      env: [FRONTEND=2.075]
    - d: dmd-2.074.1
      env: [FRONTEND=2.074]
    - d: dmd-2.073.2
      env: [FRONTEND=2.073]
    - d: dmd-2.072.2
      env: [FRONTEND=2.072]
    - d: dmd-2.071.2
      env: [FRONTEND=2.071]
    - d: dmd-2.070.2
      env: [FRONTEND=2.070]
    - d: dmd-2.069.2
      env: [FRONTEND=2.069]
    - d: dmd-2.068.2
      env: [FRONTEND=2.068]
    - d: ldc-beta
      env: [FRONTEND=2.073]
    - d: ldc-1.7.0
      env:
        - [FRONTEND=2.077]
        - [TEST_NONET=true]
    - d: ldc-1.6.0
      env: [FRONTEND=2.076]
    - d: ldc-1.5.0
      env: [FRONTEND=2.075]
    - d: ldc-1.4.0
      env: [FRONTEND=2.074]
    - d: ldc-1.3.0
      env: [FRONTEND=2.073]
    - d: ldc-1.2.0
      env: [FRONTEND=2.072]
    - d: ldc-1.1.0
      env: [FRONTEND=2.071]
    - d: ldc-1.0.0
      env: [FRONTEND=2.070]
    - d: gdc
      env: [FRONTEND=2.068]
    - d: gdc-4.8.5
      env: [FRONTEND=2.068]

  allow_failures:
    - d: gdc

addons:
  apt:
    packages:
      - libevent-dev

script:
  - deactivate # deactivate host compiler
  - ./travis-ci.sh
