language: d
sudo: false

d:
  - dmd-2.064.2
  - dmd-2.065.0
  - dmd-2.066.1
  - ldc-0.14.0
  - ldc-0.15.1
  - gdc-4.9.0

script:
  - dub test --compiler=${DC} -c library-nonet
  - dub build --compiler=${DC}
  - DUB=`pwd`/bin/dub COMPILER=${DC} test/run-unittest.sh
